version: "3.8"

services:
  openvplan:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        mode: dev
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m aiohttp_devtools runserver /app/app --verbose --static /app/static/"]
    ports:
      - "5678:5678"
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ".:/app"
      - "./config:/config:ro"
      - "./data:/var/lib/openvplan"
    environment:
      DEBUG: 1  # MUST BE 0 IN PRODUCTION
