version: "3.8"

services:
  openvplan:
    image: openvplan:latest
    ports:
      - "8000:8000"
    volumes:
      - "./config:/config:ro"
      - "./data:/var/lib/openvplan"
    environment:
      DEBUG: 0  # MUST BE 0 IN PRODUCTION

      DOMAIN: "example.org"  # REPLACE

      TITLE: "OpenVPlan"
      TITLE_BIG: "OpenVPlan"
      TITLE_MIDDLE: "OpenVPlan"
      TITLE_SMALL: "OpenVPlan"

      META_DESCRIPTION: "OpenVPlan"
      META_KEYWORDS: "OpenVPlan"

      PUBLIC_VAPID_KEY: ""  # REPLACE
      PRIVATE_VAPID_KEY: ""  # REPLACE
      VAPID_SUB: ""  # REPLACE

      PLAUSIBLE_DOMAIN: null  # REPLACE
      PLAUSIBLE_JS: "https://plausible.io/js/plausible.outbound-links.js"

      TELEGRAM_BOT_LOGGER_TOKEN: null  # REPLACE
      TELEGRAM_BOT_LOGGER_CHAT_ID: ""  # REPLACE
