version: "3.8"

services:
  gawvertretung:
    build: .
#    command:
#      - "python"
#      - "-u"
#      - "/app/server.py"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./data:/var/lib/gawvertretung
